services:
  web_api:
    image: oskidemo
    container_name: web_api_application
    ports:
      - "5000:8080"
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports: 
      - "1433:1433"
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=Pass2wor!d