services:
  web_api:
    image: oskidemo
    container_name: web_api_application
    ports:
      - "5000:8080"
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports: 
      - "1433:1433"
    environment:
      - ACCEPT_EULA=y
      - MSSQL_SA_PASSWORD=Pass2wor!d
  app:
    image: client
    container_name: angular_client
    ports:
      - "4200:4201"
    working_dir: /usr/src/app